[project]
name = "fattrace"
version = "0.0.1"
authors = [
    { name="Masataro Asai", email="guicho271828@gmail.com" },
]
description = "Informative Stacktrace that shows everything on the stack"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "ansicolors",
]

[project.urls]
Homepage = "https://github.com/guicho271828/fattrace"
Issues = "https://github.com/guicho271828/fattrace/issues"

[project.scripts]

[tool.setuptools.packages.find]
# defines where to look for sub-packages
include = ["fattrace"]

